name: Translator Service Workflow
run-name: ${{ github.actor }}'s Translator Workflow
#This workflow covers the CI/CD for the Translator portion

#Only should run on pushes to the main branch as per instructions
on: 
  push:
    branches: 
      - 'main'
      - 'master'

jobs:
  #First job is done to test and check coverage of the translator
  coverage_and_pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./translator-service
    timeout-minutes: 10

    #Which python version to run on
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: setting up recent python versions (3.8, 3.9, 3.10)
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip, install requirements
        run: | 
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 

      - name: Run Unit Tests & Coverage Analysis
        run: | 
          coverage run -m pytest ./tests/test.py > translator_test_results.txt
          python -m coverage report > translator_coverage_results.txt
        #if was useful/required, could separate each upload from each python version to different artifact

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v3
        with: 
          name: translator_coverage_results
          path: translator_coverage_results.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: translator_test_results
          path: translator_test_results.txt
          
  delivery_deployment_to_dockerhub: 
    needs: coverage_and_pytest
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into Docker
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: ./translator-service
          push: true
          tags: chiaos/se_final_project_repo:translator-latest

  deployment-to-digitalocean:
    needs: delivery_deployment_to_dockerhub
    runs-on: ubuntu-latest
    
    steps:
      - name: DigitalOcean App Platform Action
        uses: digitalocean/app_action@main
        with:
          app_name: translator-service
          token: ${{ secrets.DIGITALOCEAN_API_ACCESS }}
